---
- name: Deploy Nginx Ingress Controller and Sample Application
  hosts: webserver
  become: true
  tasks:
    - name: Deploy Nginx Ingress Controller
      become: true
      command: helm install my-release oci://ghcr.io/nginxinc/charts/nginx-ingress --version 1.1.0
      tags:
        - nginx

    - name: Deploy Sample Application
      become: true
      command: kubectl apply -f /home/ubuntu/deploy.yaml
      tags:
        - application
